export const data = [
  {
    name: "Object 1",
    id_cancha: "1",
    description: "This is the description for Object 1",
    value: 10,
    horarios: [
      {
        id_horario: "1",
        h_inicio: "14:00",
        h_fin: "15:00",
        disponible: "false",
      },
      {
        id_horario: "2",
        h_inicio: "16:00",
        h_fin: "18:00",
        disponible: "true",
      },
      {
        id_horario: "3",
        h_inicio: "22:00",
        h_fin: "23:30",
        disponible: "true",
      },
      {
        id_horario: "23",
        h_inicio: "20:00",
        h_fin: "23:30",
        disponible: "true",
      },
    ],
  },
  {
    name: "Object 2",
    id_cancha: "2",
    description: "This is the description for Object 2",
    value: 20,
    horarios: [
      {
        id_horario: "4",
        h_inicio: "14:00",
        h_fin: "15:00",
        disponible: "false",
      },
      {
        id_horario: "5",
        h_inicio: "16:00",
        h_fin: "18:00",
        disponible: "false",
      },
      {
        id_horario: "6",
        h_inicio: "22:00",
        h_fin: "23:30",
        disponible: "false",
      },
      {
        id_horario: "37",
        h_inicio: "19:00",
        h_fin: "20:30",
        disponible: "false",
      },
    ],
  },
  {
    name: "Object 3",
    id_cancha: "3",
    description: "This is the description for Object 3",
    value: 30,
    horarios: [
      {
        id_horario: "7",
        h_inicio: "19:00",
        h_fin: "20:00",
        disponible: "true",
      },
      {
        id_horario: "8",
        h_inicio: "11:00",
        h_fin: "12:00",
        disponible: "true",
      },
      {
        id_horario: "9",
        h_inicio: "20:00",
        h_fin: "22:00",
        disponible: "true",
      },
      {
        id_horario: "33",
        h_inicio: "06:00",
        h_fin: "07:30",
        disponible: "true",
      },
    ],
  },
  {
    name: "Object 8",
    id_cancha: "4",
    description: "This is the description for Object 4",
    value: 40,
    horarios: [
      {
        id_horario: "10",
        h_inicio: "16:30",
        h_fin: "17:30",
        disponible: "false",
      },
      {
        id_horario: "11",
        h_inicio: "16:00",
        h_fin: "18:00",
        disponible: "false",
      },
      {
        id_horario: "12",
        h_inicio: "22:00",
        h_fin: "23:30",
        disponible: "false",
      },
      {
        id_horario: "36",
        h_inicio: "09:00",
        h_fin: "11:30",
        disponible: "false",
      },
    ],
  },
  {
    name: "Object 5",
    id_cancha: "5",
    description: "This is the description for Object 5",
    value: 50,
    horarios: [
      {
        id_horario: "13",
        h_inicio: "14:00",
        h_fin: "15:00",
        disponible: "false",
      },
      {
        id_horario: "14",
        h_inicio: "16:00",
        h_fin: "18:00",
        disponible: "true",
      },
      {
        id_horario: "15",
        h_inicio: "22:00",
        h_fin: "23:30",
        disponible: "true",
      },
      {
        id_horario: "39",
        h_inicio: "15:00",
        h_fin: "16:30",
        disponible: "true",
      },
    ],
  },
  {
    name: "Object 5",
    id_cancha: "5",
    description: "This is the description for Object 5",
    value: 50,
    horarios: [
      {
        id_horario: "13",
        h_inicio: "14:00",
        h_fin: "15:00",
        disponible: "false",
      },
      {
        id_horario: "14",
        h_inicio: "16:00",
        h_fin: "18:00",
        disponible: "true",
      },
      {
        id_horario: "15",
        h_inicio: "22:00",
        h_fin: "23:30",
        disponible: "true",
      },
      {
        id_horario: "39",
        h_inicio: "15:00",
        h_fin: "16:30",
        disponible: "true",
      },
    ],
  },
  {
    name: "Object 5",
    id_cancha: "5",
    description: "This is the description for Object 5",
    value: 50,
    horarios: [
      {
        id_horario: "13",
        h_inicio: "14:00",
        h_fin: "15:00",
        disponible: "false",
      },
      {
        id_horario: "14",
        h_inicio: "16:00",
        h_fin: "18:00",
        disponible: "true",
      },
      {
        id_horario: "15",
        h_inicio: "22:00",
        h_fin: "23:30",
        disponible: "true",
      },
      {
        id_horario: "39",
        h_inicio: "15:00",
        h_fin: "16:30",
        disponible: "true",
      },
    ],
  },
  {
    name: "Object 5",
    id_cancha: "5",
    description: "This is the description for Object 5",
    value: 50,
    horarios: [
      {
        id_horario: "13",
        h_inicio: "14:00",
        h_fin: "15:00",
        disponible: "false",
      },
      {
        id_horario: "14",
        h_inicio: "16:00",
        h_fin: "18:00",
        disponible: "true",
      },
      {
        id_horario: "15",
        h_inicio: "22:00",
        h_fin: "23:30",
        disponible: "true",
      },
      {
        id_horario: "39",
        h_inicio: "15:00",
        h_fin: "16:30",
        disponible: "true",
      },
    ],
  },
  {
    name: "Object 5",
    id_cancha: "5",
    description: "This is the description for Object 5",
    value: 50,
    horarios: [
      {
        id_horario: "13",
        h_inicio: "14:00",
        h_fin: "15:00",
        disponible: "false",
      },
      {
        id_horario: "14",
        h_inicio: "16:00",
        h_fin: "18:00",
        disponible: "true",
      },
      {
        id_horario: "15",
        h_inicio: "22:00",
        h_fin: "23:30",
        disponible: "true",
      },
      {
        id_horario: "39",
        h_inicio: "15:00",
        h_fin: "16:30",
        disponible: "true",
      },
    ],
  },
  {
    name: "Object 5",
    id_cancha: "5",
    description: "This is the description for Object 5",
    value: 50,
    horarios: [
      {
        id_horario: "13",
        h_inicio: "14:00",
        h_fin: "15:00",
        disponible: "false",
      },
      {
        id_horario: "14",
        h_inicio: "16:00",
        h_fin: "18:00",
        disponible: "true",
      },
      {
        id_horario: "15",
        h_inicio: "22:00",
        h_fin: "23:30",
        disponible: "true",
      },
      {
        id_horario: "39",
        h_inicio: "15:00",
        h_fin: "16:30",
        disponible: "true",
      },
    ],
  },
  {
    name: "Object 5",
    id_cancha: "5",
    description: "This is the description for Object 5",
    value: 50,
    horarios: [
      {
        id_horario: "13",
        h_inicio: "14:00",
        h_fin: "15:00",
        disponible: "false",
      },
      {
        id_horario: "14",
        h_inicio: "16:00",
        h_fin: "18:00",
        disponible: "false",
      },
      {
        id_horario: "15",
        h_inicio: "22:00",
        h_fin: "23:30",
        disponible: "false",
      },
      {
        id_horario: "39",
        h_inicio: "15:00",
        h_fin: "16:30",
        disponible: "false",
      },
    ],
  },
];
